name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello!
